spring:
  profiles:
    active: usage_message
  data:
    mongodb:
      uri: ${env.MONGO_URL}
      database: ${env.MONGO_DBNAME}
  datasource:
    url: ${env.REDSHIFT_CLUSTER_DBURL}
    username: connectiontest
    password: Password123
    driver-class-name: com.amazon.redshift.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false
    hbm2ddl:
      auto: none
bulk:
  api:
    url: ${env.BULK_API_URL}
secret:
  key: LeQy09vezCNCuKOBIYPXu3uu
  dbURL: ${env.REDSHIFT_CLUSTER_DBURL}
app:
  id: 1NZ9MZFA546B7ZLQALH1K1EE
server:
  port: 8000
file:
  fieldName:
        sbf_cif: cust_id1,first_name,middle_name,surname,gender_cd,ph_nbr1,data_date,dob
    loan_portfolio: customer_id_number,cust_first_name,cust_middle_name,cust_last_name,cust_gender,cust_mob_no,data_date,cust_birth_date
  fileName:
    sbf_cif: cif
    loan_portfolio: campaign