spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:tBQU0x4KXzx5ZF9m@cluster0.erben.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: Reshift_Moengage
  datasource:
    url: jdbc:redshift://redshift-cluster-1.c474pyvxrnp3.ap-southeast-1.redshift.amazonaws.com:5439/dev
    username: connectiontest
    password: Password123
    driver-class-name: com.amazon.redshift.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false
    hbm2ddl:
      auto: none
    properties:
      hibernate:
        dialect : com.cmc.moengagedataimport.customSqlDialect.CustomSqlDialect
        current_session_context_class: thread
server:
  port: 8000

