package com.cmc.moengagedataimport.entities;

import lombok.Data;
import org.springframework.lang.Nullable;

import javax.persistence.*;

@Data
@Entity
@Table(name = "sbf_loan_portfolio")
public class SbfLoanPortfolio {
    private Integer last_repayment_date;
    private Double past_due_30;
    private String loan_purpose;
    private String cust_occupation;
    private String cust_cif_no;
    private String dosri_loan;
    private Integer cust_emergency_contact_no;
    private Integer start_inst_date;
    private Integer loan_tenor;
    private Integer no_of_day_pd;
    private Integer shrd_org_clim_appr_date;
    private Integer months_fullypyd;
    private Double all_int_paid;
    private Integer lastrepaydate_afteroverdue;
    private Integer shrd_upd_clim_appr_date;
    private String cust_employer_name;
    private String npltoperforming_reason;
    private String collateral_indictor;
    private String restructure_ind;
    private Double credit_amt_granted;
    private Double shared_undrawn_limit;
    @Id
    private Integer customer_id_number;
    private Double billed_int;
    private Double aggregated_disbursed_amt;
    private String risk_grade;
    private Integer cust_mob_no;
    private Double shrd_upd_clim_amt;
    private Integer psic_code;
    private String ccy_code;
    private Integer past_due_90;
    private String cust_emergency_contact_name;
    private Double accrued_lc;
    private String overdue_ind;
    private String npl_status;
    private Double interest_in_suspense;
    private Double amortize_installment_amt;
    private String loan_status;
    private Double write_off_amount_principal;
    private String loan_no;
    private Double int_expected;
    private String acquisition_channel_code;
    private Integer data_date;
    private Double overdue_interest;
    private Double interest_income;
    private Integer cust_industry_type;
    private Double bal_accr_int;
    private Double non_accrual_interest;
    private Integer past_due_120;
    private Integer date_lnext_pay;
    private Double repay_amt;
    private Double fees;
    private Integer cust_birth_date;
    private String write_off_indicator;
    private Double last_repayment_amount;
    private Integer past_due_180up;
    private String prod_id;
    private String cust_present_country_of_residence;
    private Double bal_accr_lc;
    private String cust_gender;
    private String cust_employment_status;
    private Double outstanding_principle;
    private Integer firstdue_afteropen;
    private Integer app_date;
    private Double ytd_interest_paid;
    private Double amount_due;
    private String agent_code;
    private String curr_bucket;
    private String prev_bucket;
    private Double mtd_interest_paid;
    private String cust_bank_relation;
    private String cust_email_id;
    private Double lastrepayamt_afteroverdue;
    private Integer past_due_180;
    private Double amt_next_pay;
    private String cust_tin;
    private Double write_off_amount_late_charges;
    private String ifrs_9_stage;
    private String cust_middle_name;
    private String cust_additional_address;
    private Double eff_interst_rate;
    private Double billed_lc;
    private String loan_sub_status;
    private Integer maturity_date;
    private String cust_present_address;
    private Double write_off_amount_interest;
    private Integer npl_date;
    private Integer past_due_150;
    private String nxt_prin_pay_due_date;
    private Double accrued_int;
    private Double normal_interest_rate;
    private String cust_name;
    private String cust_marital_status;
    private Integer currbatch_date;
    private Integer customer_id_type;
    private String nxt_int_pay_due_date;
    private Integer past_due_60;
    private Double disbursed_amt;
    private Double all_int_accr;
    private String cust_first_name;
    private String pay_history;
    private Integer write_off_date;
    private String cust_last_name;
    private Double shrd_ort_clim_amt;
}